export const MUNICIPIOS_ANTIOQUIA = [
  'Abejorral','Abriaquí','Alejandría','Amagá','Amalfi','Andes','Angelópolis',
  'Angostura','Anorí','Anzá','Apartadó','Arboletes','Argelia','Armenia',
  'Barbosa','Bello','Belmira','Betania','Betulia','Briceño','Buriticá','Cáceres',
  'Caicedo','Caldas','Campamento','Cañasgordas','Caracolí','Caramanta',
  'Carepa','Carolina del Príncipe','Caucasia','Chigorodó','Cisneros',
  'Ciudad Bolívar','Cocorná','Concepción','Concordia','Copacabana','Dabeiba',
  'Don Matías','Ebéjico','El Bagre','El Carmen de Viboral','El Peñol',
  'El Retiro','El Santuario','Entrerríos','Envigado','Fredonia','Frontino',
  'Giraldo','Girardota','Gómez Plata','Granada','Guadalupe','Guarne','Guatapé',
  'Heliconia','Hispania','Itagüí','Ituango','Jardín','Jericó','La Ceja',
  'La Estrella','La Pintada','La Unión','Liborina','Maceo','Marinilla',
  'Medellín','Montebello','Murindó','Mutatá','Nariño','Nechí','Necoclí',
  'Olaya','Peque','Pueblorrico','Puerto Berrío','Puerto Nare','Puerto Triunfo',
  'Remedios','Rionegro','Sabanalarga','Sabaneta','Salgar','San Andrés de Cuerquia',
  'San Carlos','San Francisco','San Jerónimo','San José de la Montaña',
  'San Juan de Urabá','San Luis','San Pedro de los Milagros','San Pedro de Urabá',
  'San Rafael','San Roque','San Vicente Ferrer','Santa Bárbara',
  'Santa Fe de Antioquia','Santa Rosa de Osos','Santo Domingo','Segovia',
  'Sonsón','Sopetrán','Támesis','Tarazá','Tarso','Titiribí','Toledo',
  'Turbo','Uramita','Urrao','Valdivia','Valparaíso','Vegachí','Venecia',
  'Vigía del Fuerte','Yalí','Yarumal','Yolombó','Yondó','Zaragoza',
].sort()
